// Like vtkColorMaps.rgbPresetNames, but more selective
const ColorMapPresetNames = [
  'Viridis (matplotlib)',
  'Plasma (matplotlib)',
  'Inferno (matplotlib)',
  'Magma (matplotlib)',
  'Grayscale',
  'X Ray',
  'magenta',
  'blue2cyan',
  'gray_Matlab',
  'bone_Matlab',
  'pink_Matlab',
  '2hot',
  'gist_earth',
  'Haze',
  'Haze_green',
  'Haze_lime',
  'Haze_cyan',
  'Black, Blue and White',
  'Black, Orange and White',
  'Black-Body Radiation',

  'Cool to Warm',
  'Warm to Cool',
  'Cool to Warm (Extended)',
  'Warm to Cool (Extended)',
  'Blue to Red Rainbow',
  'Red to Blue Rainbow',
  'jet',
  'rainbow',
  'hsv',
  'Rainbow Desaturated',
  'Cold and Hot',
  'Rainbow Blended Black',
  'Rainbow Blended Grey',
  'Rainbow Blended White',
  'nic_CubicL',
  'Spectral_lowBlue',
  'Yellow 15',
  'Asymmtrical Earth Tones (6_21b)',
  'Green-Blue Asymmetric Divergent (62Blbc)',
  'Muted Blue-Green',

  'Reds',
  'Greens',
  'Blues',
  'Purples',
  'Oranges',
  'PuBu',
  'BuPu',
  'BuGn',
  'GnBu',
  'PuRd',
  'RdPu',
  'RdOr',
  'BuRd',
  'GnRP',
  'GYPi',
  'GBBr',
  'PRGn',
  'PiYG',
  'OrPu',
  'BrBG',
];

export default ColorMapPresetNames;
