const CategoricalPresetIcons = new Map()

CategoricalPresetIcons.set(
  'glasbey',
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAAFCAYAAAAZiY8XAAAAbUlEQVQ4T2O8zsDwnwENbLXBEGIo82FEV8bwT+U4htiMYEsMsfSGixhiuY11GGKTlz7EEIucdgFDbIVMJIYYw8oWTLG/nzDEGK8zMPyjuYcbsXi4YeA8/JfmHh5kMfyH5h4eZDH8m+YeHkQxDACSRl3zepXFtQAAAABJRU5ErkJggg=='
)

CategoricalPresetIcons.set(
  'glasbey_light',
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAAFCAYAAAAZiY8XAAAAXUlEQVQ4T2O8zsDwnwENaHegizAwbKnAUMYQsOY4hsJJwVYYYunLDDANfDUDQ6zq8HQMsfY1BRhiG5ZjmveEoxVDHdueGgwxxusMDP9Gmof/jjQP/xlpHv49kjwMAGwvWgYDwlVYAAAAAElFTkSuQmCC'
)

CategoricalPresetIcons.set(
  'glasbey_warm',
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAAFCAYAAAAZiY8XAAAAXklEQVQ4T2O8zsDwnwENaCT9QBdiWGvNgSF2IrkQQ+yuZz+G2LrATgyxSdcZMcTyGp5hiF3kF8QQ22S1EUOstuMQhtjuVTYYYozXGRj+jTQP/x1pHv4z0jz8eyR5GAB6w1ulCOS6owAAAABJRU5ErkJggg=='
)

CategoricalPresetIcons.set(
  'modulate',
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAAFCAYAAAAZiY8XAAAAJ0lEQVQ4T+XPBw0AAAjAMPAvmTOCjtVBEyBEEljRNz48tnDbwmUKHxUmE+jjOrX6AAAAAElFTkSuQmCC'
)

CategoricalPresetIcons.set(
  'glasbey_bw',
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAAFCAYAAAAZiY8XAAAAbUlEQVQ4T2O8zsDwnwENbLXBEGIo82FEV8bwT+U4htiMYEsMsfSGixhiuY11GGKTlz7EEGOMzsUQays4jSFWdfMWhpj/w32Y5l1nYPhHcw83YvFww8B5+C/NPTzIYvgPzT08yGL4N809PIhiGADz42FUcjTZogAAAABJRU5ErkJggg=='
)

CategoricalPresetIcons.set(
  'glasbey_dark',
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAAFCAYAAAAZiY8XAAAAbklEQVQ4T2O8zsDwnwENbLXBEGIo82FEV8bwT+U4htjzn5YYYhK3LmKI5TbWYYi9sd6IIbZCJhJDTLTLBEPstXwAhtiisl4MMcbrDAz/aO7h21g83DBwHv5Lcw8Pshj+Q3MPD7IY/k1zDw+iGAYAOVBcgZzUS9MAAAAASUVORK5CYII='
)

CategoricalPresetIcons.set(
  'glasbey_cool',
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAAFCAYAAAAZiY8XAAAAcElEQVQ4T2Pkzfr/nwEN/NH2Qxdi+G46A0PMy3QNhti2yPMYYmt95mOInTg3AUPsep8+hpj/7ocYYr9cgjHtmIBpx75t/RjqGHmz/v8baR7+O9I8/Gekefg3dT18DkseXkBBHn6EJQ8HEZmH+zDUAQAnhWrvPnCKfAAAAABJRU5ErkJggg=='
)

CategoricalPresetIcons.set(
  'modulate_dark',
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAAFCAYAAAAZiY8XAAAAJklEQVQ4T+XPBw0AAAjAsOFfMjfoWB00gEUkgBF9+XDbwmULpyl8/eAE9wt5lvIAAAAASUVORK5CYII='
)

export default CategoricalPresetIcons
