(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
function isPromise(o){return!!o&&("object"==typeof o||"function"==typeof o)&&"function"==typeof o.then}module.exports=isPromise;
},{}],2:[function(require,module,exports){
"use strict";function registerPromiseWorker(e){function r(e,r,s,n){function t(r,s){"function"!=typeof self.postMessage?e.ports[0].postMessage(r,s):self.postMessage(r,s)}s?("undefined"!=typeof console&&"error"in console&&console.error("Worker caught an error:",s),t([r,{message:s.message}])):n instanceof i?t([r,null,n.message],n.transferList):t([r,null,n])}function s(e,r){try{return{res:e(r,n)}}catch(e){return{err:e}}}function n(e,r){return new i(e,r)}function t(e,n,t,o){var i=s(n,o);i.err?r(e,t,i.err):isPromise(i.res)?i.res.then(function(s){r(e,t,null,s)},function(s){r(e,t,s)}):r(e,t,null,i.res)}function o(s){var n=s.data;if(Array.isArray(n)&&2===n.length){var o=n[0],i=n[1];"function"!=typeof e?r(s,o,new Error("Please pass a function into register().")):t(s,e,o,i)}}function i(e,r){this.message=e,this.transferList=r}self.addEventListener("message",o)}var isPromise=require("is-promise");module.exports=registerPromiseWorker;
},{"is-promise":1}],3:[function(require,module,exports){
"use strict";var registerPromiseWorker=require("promise-worker-transferable/register"),ImageType=require("../itkImageType.js"),Image=require("../itkImage.js"),mimeToIO=require("../itkMimeToIO.js"),getFileExtension=require("../itkgetFileExtension.js"),extensionToIO=require("../itkExtensionToIO.js"),readImageEmscriptenFSFile=require("../itkreadImageEmscriptenFSFile.js"),config=require("../itkConfig.js"),ioToModule={};registerPromiseWorker(function(e,r){var i=getFileExtension(e.name),o=null;if(mimeToIO.hasOwnProperty(e.type)?o=mimeToIO[e.type]:extensionToIO.hasOwnProperty(i)&&(o=extensionToIO[i]),null===o)return Error("Could not find IO for: "+e.name);var n=null;if(o in ioToModule)n=ioToModule[o];else{var t=config.imageIOsPath+"/"+o+".js";importScripts(t),ioToModule[o]=Module,n=Module}var s=new Blob([e.buffer]),a=[{name:e.name,data:s}];n.mountBlobs("/work",a);var m="/work/"+e.name,u=readImageEmscriptenFSFile(n,m);return n.unmountBlobs("/work"),r(u,[u.buffer.buffer])});

},{"../itkConfig.js":4,"../itkExtensionToIO.js":5,"../itkImage.js":7,"../itkImageType.js":8,"../itkMimeToIO.js":11,"../itkgetFileExtension.js":13,"../itkreadImageEmscriptenFSFile.js":14,"promise-worker-transferable/register":2}],4:[function(require,module,exports){
"use strict";var config={imageIOsPath:"/itkImageIOs",webWorkersPath:"/itkWebWorkers"};module.exports=config;

},{}],5:[function(require,module,exports){
"use strict";var extensionToIO={};extensionToIO.dcm="itkGDCMImageIOJSBinding",extensionToIO.DCM="itkGDCMImageIOJSBinding",extensionToIO.mha="itkMetaImageIOJSBinding",extensionToIO.mhd="itkMetaImageIOJSBinding",extensionToIO.nrrd="itkNrrdImageIOJSBinding",extensionToIO.NRRD="itkNrrdImageIOJSBinding",extensionToIO.nhdr="itkNrrdImageIOJSBinding",extensionToIO.NHDR="itkNrrdImageIOJSBinding",extensionToIO.png="itkPNGImageIOJSBinding",extensionToIO.PNG="itkPNGImageIOJSBinding",extensionToIO.tif="itkTIFFImageIOJSBinding",extensionToIO.TIF="itkTIFFImageIOJSBinding",extensionToIO.tiff="itkTIFFImageIOJSBinding",extensionToIO.TIFF="itkTIFFImageIOJSBinding",extensionToIO.vtk="itkVTKImageIOJSBinding",extensionToIO.VTK="itkVTKImageIOJSBinding",module.exports=extensionToIO;

},{}],6:[function(require,module,exports){
"use strict";var Float32="float",Float64="double",SpacePrecisionType="double";module.exports={Float32:Float32,Float64:Float64,SpacePrecisionType:SpacePrecisionType};

},{}],7:[function(require,module,exports){
"use strict";var ImageType=require("./itkImageType.js"),Matrix=require("./itkMatrix.js"),Image=function(){var i=arguments.length>0&&void 0!==arguments[0]?arguments[0]:new ImageType;this.imageType=i;var e=i.dimension;this.origin=new Array(e),this.origin.fill(0),this.spacing=new Array(e),this.spacing.fill(1),this.direction=new Matrix(e,e),this.direction.setIdentity(),this.size=new Array(e),this.size.fill(0),this.buffer=new ArrayBuffer(0)};module.exports=Image;

},{"./itkImageType.js":8,"./itkMatrix.js":10}],8:[function(require,module,exports){
"use strict";var IntTypes=require("./itkIntTypes.js"),PixelTypes=require("./itkPixelTypes.js"),ImageType=function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:2,i=arguments.length>1&&void 0!==arguments[1]?arguments[1]:IntTypes.UInt8,t=arguments.length>2&&void 0!==arguments[2]?arguments[2]:PixelTypes.Scalar,s=arguments.length>3&&void 0!==arguments[3]?arguments[3]:1;this.dimension=e,this.componentType=i,this.pixelType=t,this.components=s};module.exports=ImageType;

},{"./itkIntTypes.js":9,"./itkPixelTypes.js":12}],9:[function(require,module,exports){
"use strict";var Int8="int8_t",UInt8="uint8_t",Int16="int16_t",UInt16="uint16_t",Int32="int32_t",UInt32="uint32_t",Int64="int64_t",UInt64="uint64_t",SizeValueType=UInt64,IdentifierType=SizeValueType,IndexValueType=Int64,OffsetValueType=Int64;module.exports={Int8:Int8,UInt8:UInt8,Int16:Int16,UInt16:UInt16,Int32:Int32,UInt32:UInt32,Int64:Int64,UInt64:UInt64,SizeValueType:SizeValueType,IdentifierType:IdentifierType,IndexValueType:IndexValueType,OffsetValueType:OffsetValueType};

},{}],10:[function(require,module,exports){
"use strict";function Matrix(t,s){if(t instanceof Matrix){var i=t;this.rows=i.rows,this.columns=i.columns,this.data=i.data.slice()}else this.rows=t,this.columns=s,this.data=new Array(t*s),this.data.fill(0)}Matrix.prototype.setIdentity=function(){for(var t=0;t<this.rows;++t)for(var s=0;s<this.columns;++s)this.data[s+t*this.columns]=t===s?1:0},Matrix.prototype.setElement=function(t,s,i){this.data[s+t*this.columns]=i},Matrix.prototype.getElement=function(t,s){return this.data[s+t*this.columns]},module.exports=Matrix;

},{}],11:[function(require,module,exports){
"use strict";var mimeToIO={};mimeToIO["image/png"]="itkPNGImageIOJSBinding",mimeToIO["image/tiff"]="itkTIFFImageIOJSBinding",mimeToIO["application/dicom"]="itkGDCMImageIOJSBinding",module.exports=mimeToIO;

},{}],12:[function(require,module,exports){
"use strict";var Unknown=0,Scalar=1,RGB=2,RGBA=3,Offset=4,Vector=5,Point=6,CovariantVector=7,SymmetricSecondRankTensor=8,DiffusionTensor3D=9,Complex=10,FixedArray=11,Matrix=12;module.exports={Unknown:Unknown,Scalar:Scalar,RGB:RGB,RGBA:RGBA,Offset:Offset,Vector:Vector,Point:Point,CovariantVector:CovariantVector,SymmetricSecondRankTensor:SymmetricSecondRankTensor,DiffusionTensor3D:DiffusionTensor3D,Complex:Complex,FixedArray:FixedArray,Matrix:Matrix};

},{}],13:[function(require,module,exports){
"use strict";var getFileExtension=function(e){return e.slice(2+(e.lastIndexOf(".")-1>>>0))};module.exports=getFileExtension;

},{}],14:[function(require,module,exports){
"use strict";var Image=require("./itkImage.js"),ImageType=require("./itkImageType.js"),IntTypes=require("./itkIntTypes.js"),FloatTypes=require("./itkFloatTypes.js"),PixelTypes=require("./itkPixelTypes.js"),Matrix=require("./itkMatrix.js"),readImageEmscriptenFSFile=function(e,n){var p=new e.ITKImageIO;if(p.SetFileName(n),!p.CanReadFile(n))return null;p.ReadImageInformation();var i=p.GetNumberOfDimensions(),t=new ImageType(i);switch(p.GetComponentType()){case e.IOComponentType.UCHAR:t.componentType=IntTypes.UInt8;break;case e.IOComponentType.CHAR:t.componentType=IntTypes.Int8;break;case e.IOComponentType.USHORT:t.componentType=IntTypes.UInt16;break;case e.IOComponentType.SHORT:t.componentType=IntTypes.Int16;break;case e.IOComponentType.UINT:t.componentType=IntTypes.UInt32;break;case e.IOComponentType.INT:t.componentType=IntTypes.Int32;break;case e.IOComponentType.ULONG:t.componentType=IntTypes.UInt64;break;case e.IOComponentType.LONG:t.componentType=IntTypes.Int64;break;case e.IOComponentType.FLOAT:t.componentType=FloatTypes.Float32;break;case e.IOComponentType.DOUBLE:t.componentType=FloatTypes.Float64;break;default:return console.error("Unknown IO component type"),null}switch(p.GetPixelType()){case e.IOPixelType.UNKNOWNPIXELTYPE:t.pixelType=PixelTypes.Unknown;break;case e.IOPixelType.SCALAR:t.pixelType=PixelTypes.Scalar;break;case e.IOPixelType.RGB:t.pixelType=PixelTypes.RGB;break;case e.IOPixelType.RGBA:t.pixelType=PixelTypes.RGBA;break;case e.IOPixelType.OFFSET:t.pixelType=PixelTypes.Offset;break;case e.IOPixelType.VECTOR:t.pixelType=PixelTypes.Vector;break;case e.IOPixelType.POINT:t.pixelType=PixelTypes.Point;break;case e.IOPixelType.COVARIANTVECTOR:t.pixelType=PixelTypes.CovariantVector;break;case e.IOPixelType.SYMMETRICSECONDRANKTENSOR:t.pixelType=PixelTypes.SymmetricSecondRankTensor;break;case e.IOPixelType.DIFFUSIONTENSOR3D:t.pixelType=PixelTypes.DiffusionTensor3D;break;case e.IOPixelType.COMPLEX:t.pixelType=PixelTypes.Complex;break;case e.IOPixelType.FIXEDARRAY:t.pixelType=PixelTypes.FixedArray;break;case e.IOPixelType.MATRIX:t.pixelType=PixelTypes.Matrix;break;default:return console.error("Unknown IO pixel type"),null}t.components=p.GetNumberOfComponents();for(var a=new Image(t),T=new Matrix(i,i),o=0;o<i;++o)for(var r=p.GetDirection(o),s=0;s<i;++s)T.setElement(s,o,r.get(s));for(var y=0;y<a.imageType.dimension;++y)if(y<i){a.size[y]=p.GetDimensions(y),a.spacing[y]=p.GetSpacing(y),a.origin[y]=p.GetOrigin(y);for(var l=0;l<a.imageType.dimension;++l)if(l<i){var I=T.getElement(l,y);a.direction.setElement(l,y,I)}else a.direction.setElement(l,y,0)}else a.size[y]=0,a.spacing[y]=1,a.origin[y]=0,a.direction.setIdentity();for(var c=0;c<a.imageType.dimension;++c)if(a.spacing[c]<0){a.spacing[c]=-a.spacing[c];for(var m=0;m<a.imageType.dimension;++m)a.direction.setElement(c,m,-1*a.direction.getElement(c,m))}return a.buffer=p.Read(),a};module.exports=readImageEmscriptenFSFile;

},{"./itkFloatTypes.js":6,"./itkImage.js":7,"./itkImageType.js":8,"./itkIntTypes.js":9,"./itkMatrix.js":10,"./itkPixelTypes.js":12}]},{},[3]);
